import type { FileToolDependencies } from "./types.js";

/** Color tokens used by the three supported Word document themes. */
const THEMES = {
  neutral: { primary: "334155", accent: "64748B", text: "1E293B" },
  blue: { primary: "1E40AF", accent: "3B82F6", text: "172554" },
  warm: { primary: "92400E", accent: "D97706", text: "451A03" },
};
/** Word page margins in twentieths of a point (DXA). */
const MARGINS = { normal: 1440, narrow: 720, wide: 2160 };

/**
 * Converts Markdown/plain text into a complete DOCX binary.
 * @param input Document content, styling, host dependencies, and cancellation signal.
 * @returns Packed DOCX buffer.
 */
export async function renderDocx(input: {
  content: string;
  title: string;
  subtitle?: string | null;
  author?: string | null;
  theme: keyof typeof THEMES;
  margins: keyof typeof MARGINS;
  includeTitlePage: boolean;
  dependencies: FileToolDependencies;
  signal?: AbortSignal;
}): Promise<Buffer> {
  // Lazy loading avoids startup cost when the agent never creates a DOCX file.
  const packages = ["marked", "jsdom", "docx"];
  const [markedModule, jsdomModule, docxModule] = await Promise.all(
    packages.map(
      /** Imports one renderer dependency by package name. */
      (name) => import(name)
    )
  );
  const { marked } = markedModule;
  const { JSDOM } = jsdomModule;
  const d: any = docxModule;
  // Markdown becomes HTML first so block and inline conversion stay separate.
  marked.setOptions({ gfm: true, breaks: true });
  const dom = new JSDOM(`<body>${marked.parse(input.content)}</body>`);
  const theme = THEMES[input.theme];
  const children = await htmlChildren(
    dom.window.document.body,
    d,
    theme,
    input.dependencies,
    input.signal
  );
  const margin = {
    top: MARGINS[input.margins],
    right: MARGINS[input.margins],
    bottom: MARGINS[input.margins],
    left: MARGINS[input.margins],
  };
  // Host branding is optional; the footer remains valid without a logo.
  const logo = input.dependencies.getLogo?.({
    forDarkBackground: false,
    format: "buffer",
  });
  const footer = new d.Footer({
    children: [
      new d.Paragraph({
        alignment: d.AlignmentType.CENTER,
        children: [
          new d.TextRun("Page "),
          new d.TextRun({ children: [d.PageNumber.CURRENT] }),
          new d.TextRun(" of "),
          new d.TextRun({ children: [d.PageNumber.TOTAL_PAGES] }),
        ],
      }),
    ],
  });
  // A title page is a separate section so its header can differ from content.
  const sections: any[] = [];
  if (input.includeTitlePage) {
    const coverChildren: any[] = [
      new d.Paragraph({
        spacing: { before: 3600 },
        alignment: d.AlignmentType.CENTER,
        children: [
          new d.TextRun({
            text: input.title,
            bold: true,
            size: 48,
            color: theme.primary,
          }),
        ],
      }),
    ];
    if (input.subtitle)
      coverChildren.push(
        new d.Paragraph({
          alignment: d.AlignmentType.CENTER,
          children: [
            new d.TextRun({
              text: input.subtitle,
              size: 28,
              color: theme.accent,
            }),
          ],
        })
      );
    if (input.author)
      coverChildren.push(
        new d.Paragraph({
          alignment: d.AlignmentType.CENTER,
          spacing: { before: 720 },
          children: [new d.TextRun(input.author)],
        })
      );
    sections.push({
      properties: { page: { margin } },
      children: coverChildren,
    });
  }
  const header = input.includeTitlePage
    ? new d.Header({
        children: [
          new d.Paragraph({
            children: [
              new d.TextRun({ text: input.title, color: theme.accent }),
            ],
          }),
        ],
      })
    : undefined;
  sections.push({
    properties: { page: { margin } },
    headers: header ? { default: header } : undefined,
    footers: { default: footer },
    children: children.length ? children : [new d.Paragraph(input.content)],
  });
  // Numbering levels support nested ordered lists generated by Markdown.
  const document = new d.Document({
    title: input.title,
    creator:
      `Document Tool ${input.dependencies.getDeploymentVersion?.() ?? ""}`.trim(),
    numbering: {
      config: [
        {
          reference: "default-numbering",
          levels: Array.from(
            { length: 6 },
            /** Creates one ordered-list definition per nesting level. */
            (_, level) => ({
              level,
              format: "decimal",
              text: `%${level + 1}.`,
              alignment: "start",
              style: {
                paragraph: {
                  indent: { left: 720 * (level + 1), hanging: 360 },
                },
              },
            })
          ),
        },
      ],
    },
    sections,
  });
  return Buffer.from(await d.Packer.toBuffer(document));
}

/**
 * Converts top-level HTML block nodes into docx paragraphs and tables.
 * @param root JSDOM root containing rendered Markdown HTML.
 * @param d Loaded `docx` module namespace.
 * @param theme Resolved Word color theme.
 * @param dependencies Host adapters for optional assets and remote images.
 * @param signal Optional cancellation signal for image retrieval.
 * @returns DOCX child elements in source order.
 */
async function htmlChildren(
  root: any,
  d: any,
  theme: any,
  dependencies: FileToolDependencies,
  signal?: AbortSignal
): Promise<any[]> {
  const output: any[] = [];
  for (const node of Array.from(root.childNodes) as any[]) {
    // Ignore comments and whitespace-only DOM text between block elements.
    if (node.nodeType !== 1) continue;
    const tag = node.tagName.toLowerCase();
    if (/^h[1-6]$/.test(tag)) {
      output.push(
        new d.Paragraph({
          heading: d.HeadingLevel[`HEADING_${tag[1]}`],
          children: await inlineRuns(node, d, {}, dependencies, signal),
          thematicBreak: false,
        })
      );
    } else if (tag === "ul" || tag === "ol") {
      // Lists need block recursion; inline traversal would flatten nested items.
      output.push(...(await listParagraphs(node, d, dependencies, signal)));
    } else if (tag === "pre") {
      output.push(
        new d.Paragraph({
          shading: { fill: "F1F5F9" },
          children: [
            new d.TextRun({
              text: node.textContent ?? "",
              font: "Courier New",
              size: 18,
            }),
          ],
        })
      );
    } else if (tag === "blockquote") {
      output.push(
        new d.Paragraph({
          indent: { left: 500 },
          border: {
            left: {
              color: theme.accent,
              size: 12,
              style: d.BorderStyle.SINGLE,
            },
          },
          children: await inlineRuns(node, d, {}, dependencies, signal),
        })
      );
    } else if (tag === "table") {
      // Each HTML row/cell maps directly to one OOXML table row/cell.
      const rows = [];
      for (const row of Array.from(node.querySelectorAll("tr")) as any[]) {
        const cells = [];
        for (const cell of Array.from(row.children) as any[])
          cells.push(
            new d.TableCell({
              children: [
                new d.Paragraph({
                  children: await inlineRuns(cell, d, {}, dependencies, signal),
                }),
              ],
            })
          );
        rows.push(new d.TableRow({ children: cells }));
      }
      output.push(
        new d.Table({
          width: { size: 100, type: d.WidthType.PERCENTAGE },
          rows,
        })
      );
    } else if (tag === "hr") {
      output.push(
        new d.Paragraph({
          border: {
            bottom: {
              color: theme.accent,
              size: 8,
              style: d.BorderStyle.SINGLE,
            },
          },
        })
      );
    } else
      output.push(
        new d.Paragraph({
          children: await inlineRuns(node, d, {}, dependencies, signal),
        })
      );
  }
  return output;
}

/**
 * Converts inline HTML nodes into docx text, link, break, and image runs.
 * @param node HTML node to traverse.
 * @param d Loaded `docx` module namespace.
 * @param style Formatting inherited from ancestor inline tags.
 * @param dependencies Host adapters for safe remote images.
 * @param signal Optional cancellation signal.
 * @returns DOCX run elements.
 */
async function inlineRuns(
  node: any,
  d: any,
  style: Record<string, any> = {},
  dependencies: FileToolDependencies,
  signal?: AbortSignal
): Promise<any[]> {
  const runs: any[] = [];
  for (const child of Array.from(node.childNodes) as any[]) {
    if (child.nodeType === 3)
      runs.push(new d.TextRun({ text: child.textContent ?? "", ...style }));
    else if (child.nodeType === 1) {
      const tag = child.tagName.toLowerCase();
      if (tag === "br") runs.push(new d.TextRun({ break: 1 }));
      else if (
        tag === "a" &&
        /^https?:\/\//i.test(child.getAttribute("href") ?? "")
      )
        runs.push(
          new d.ExternalHyperlink({
            link: child.getAttribute("href"),
            children: [
              new d.TextRun({
                text: child.textContent ?? "",
                style: "Hyperlink",
                color: "0563C1",
                underline: { type: "single" },
              }),
            ],
          })
        );
      else if (tag === "img") {
        // Remote bytes are fetched only through the host's SSRF-safe adapter.
        const image = await fetchImage(
          child.getAttribute("src"),
          dependencies,
          signal
        );
        if (image)
          runs.push(
            new d.ImageRun({
              data: image.buffer,
              type: image.type,
              transformation: { width: 400, height: 300 },
            })
          );
      } else
        // Formatting flags accumulate while recursively descending inline tags.
        runs.push(
          ...(await inlineRuns(
            child,
            d,
            {
              ...style,
              bold: style.bold || tag === "strong" || tag === "b",
              italics: style.italics || tag === "em" || tag === "i",
              strike: style.strike || tag === "s" || tag === "del",
              font: tag === "code" ? "Consolas" : undefined,
            },
            dependencies,
            signal
          ))
        );
    }
  }
  return runs;
}

/**
 * Decodes a bounded data image or delegates safe remote retrieval to the host.
 * @param src Image data URI or HTTP(S) URL.
 * @param dependencies Host SSRF-safe remote-image adapter.
 * @param signal Optional cancellation signal.
 * @returns Validated image bytes/type, or `null` when unsupported or unavailable.
 */
async function fetchImage(
  src: string | null,
  dependencies: FileToolDependencies,
  signal?: AbortSignal
): Promise<{ buffer: Buffer; type: "png" | "jpg" | "gif" } | null> {
  if (!src) return null;
  let buffer: Buffer;
  if (/^data:image\/(png|jpeg|jpg|gif);base64,/i.test(src))
    buffer = Buffer.from(src.split(",", 2)[1], "base64");
  else if (/^https?:\/\//i.test(src)) {
    // The host must block private networks, unsafe redirects, and oversized streams.
    if (!dependencies.fetchRemoteImage) return null;
    const remote = await dependencies.fetchRemoteImage({
      url: src,
      maxBytes: 5 * 1024 * 1024,
      timeoutMs: 10_000,
      signal,
    });
    if (!remote) return null;
    buffer = remote;
  } else return null;
  // Verify size and magic bytes before embedding untrusted image data in OOXML.
  if (!buffer.length || buffer.length > 5 * 1024 * 1024) return null;
  if (
    buffer
      .subarray(0, 8)
      .equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))
  )
    return { buffer, type: "png" };
  if (buffer[0] === 0xff && buffer[1] === 0xd8) return { buffer, type: "jpg" };
  if (buffer.subarray(0, 3).toString() === "GIF")
    return { buffer, type: "gif" };
  return null;
}

/**
 * Recursively renders ordered and unordered list items at their real depth.
 * @param list HTML `ul` or `ol` element.
 * @param d Loaded `docx` module namespace.
 * @param dependencies Host adapters for inline image rendering.
 * @param signal Optional cancellation signal.
 * @param level Current nesting depth.
 * @returns List paragraphs in document reading order.
 */
async function listParagraphs(
  list: any,
  d: any,
  dependencies: FileToolDependencies,
  signal?: AbortSignal,
  level = 0
): Promise<any[]> {
  const output: any[] = [];
  for (const item of Array.from(list.children) as any[]) {
    // Clone only direct content so nested lists become separate paragraphs.
    const directContent = item.cloneNode(false);
    for (const child of Array.from(item.childNodes) as any[])
      if (!(child.nodeType === 1 && /^(ul|ol)$/i.test(child.tagName)))
        directContent.appendChild(child.cloneNode(true));
    output.push(
      new d.Paragraph({
        bullet: list.tagName.toLowerCase() === "ul" ? { level } : undefined,
        numbering:
          list.tagName.toLowerCase() === "ol"
            ? { reference: "default-numbering", level }
            : undefined,
        children: await inlineRuns(directContent, d, {}, dependencies, signal),
      })
    );
    // Recurse after the parent item to preserve document reading order.
    for (const nested of Array.from(item.children) as any[])
      if (/^(ul|ol)$/i.test(nested.tagName))
        output.push(
          ...(await listParagraphs(nested, d, dependencies, signal, level + 1))
        );
  }
  return output;
}
