import type { FileToolDependencies } from "./types.js";
import { PPTX_THEMES, type PptxThemeName } from "./pptx-themes.js";

/** Structured slide payload submitted by a presentation section child agent. */
export interface SlideData {
  layout: "section" | "content" | "blank";
  title: string;
  subtitle?: string;
  content?: string[];
  notes?: string;
  table?: { headers: string[]; rows: string[][] };
}

/**
 * Builds a widescreen PowerPoint deck from normalized structured slides.
 * @param input Deck metadata, theme, slides, and host branding dependency.
 * @returns Packed PPTX buffer.
 */
export async function renderPptx(input: {
  title: string;
  author: string;
  theme: PptxThemeName;
  slides: SlideData[];
  dependencies: FileToolDependencies;
}): Promise<Buffer> {
  // Load PptxGenJS only when the public PPTX tool is selected.
  const packageName = "pptxgenjs";
  const module = await import(packageName);
  const PptxGenJS: any = module.default ?? module;
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";
  pptx.title = input.title;
  pptx.author = input.author;
  const theme = PPTX_THEMES[input.theme];
  // The title slide is parent-owned and never generated by section agents.
  const titleSlide = pptx.addSlide();
  baseSlide(
    titleSlide,
    pptx,
    theme,
    0,
    input.slides.length + 1,
    input.dependencies
  );
  titleSlide.addText(input.title, {
    x: 0.8,
    y: 2.15,
    w: 11.7,
    h: 1,
    fontSize: 34,
    bold: true,
    align: "center",
    color: theme.primary,
    margin: 0.05,
  });
  if (input.author)
    titleSlide.addText(input.author, {
      x: 1,
      y: 3.25,
      w: 11.3,
      h: 0.4,
      fontSize: 16,
      align: "center",
      color: theme.muted,
    });
  input.slides.forEach(
    /** Renders one structured child-agent payload into a deck slide. */
    (data, index) => {
      // Every generated slide receives shared theme, progress, and branding chrome.
      const slide = pptx.addSlide();
      baseSlide(
        slide,
        pptx,
        theme,
        index + 1,
        input.slides.length + 1,
        input.dependencies
      );
      if (data.layout === "blank") {
        // Blank slides intentionally contain only base chrome and speaker notes.
        if (data.notes) slide.addNotes(data.notes);
        return;
      }
      if (data.layout === "section") {
        slide.addText(data.title, {
          x: 0.9,
          y: 2.1,
          w: 11.5,
          h: 0.8,
          fontSize: 30,
          bold: true,
          align: "center",
          color: theme.primary,
        });
        if (data.subtitle)
          slide.addText(data.subtitle, {
            x: 1.2,
            y: 3,
            w: 10.9,
            h: 0.5,
            fontSize: 17,
            align: "center",
            color: theme.muted,
          });
      } else {
        slide.addText(data.title, {
          x: 0.7,
          y: 0.35,
          w: 11.9,
          h: 0.55,
          fontSize: 26,
          bold: true,
          color: theme.primary,
          margin: 0,
        });
        // Bound bullets and tables so model output cannot overflow the slide wildly.
        const bullets = (data.content ?? []).slice(0, 8).map(
          /** Converts one content string into a PptxGenJS bullet run. */
          (text) => ({
            text,
            options: { bullet: { indent: 18 }, hanging: 4, breakLine: true },
          })
        );
        slide.addText(bullets, {
          x: 0.85,
          y: 1.2,
          w: data.table ? 6.1 : 11.4,
          h: 5.2,
          fontSize: bullets.length > 6 ? 16 : 20,
          color: theme.text,
          breakLine: true,
          valign: "top",
          margin: 0.08,
          paraSpaceAfterPt: 9,
        });
        if (data.table)
          slide.addTable(
            [data.table.headers, ...data.table.rows.slice(0, 12)],
            {
              x: 7.15,
              y: 1.3,
              w: 5.35,
              h: 4.7,
              fontSize: 10,
              color: theme.text,
              border: { type: "solid", color: theme.muted, pt: 0.5 },
              fill: theme.background,
              rowH: 0.28,
              margin: 0.04,
            }
          );
      }
      if (data.notes) slide.addNotes(data.notes);
    }
  );
  return Buffer.from(await pptx.write({ outputType: "nodebuffer" }));
}

/**
 * Applies shared background, accent, numbering, and optional logo branding.
 * @param slide PptxGenJS slide to decorate.
 * @param pptx PptxGenJS presentation instance for shape constants.
 * @param theme Resolved presentation theme.
 * @param number One-based content slide number; zero disables numbering.
 * @param total Total slide count including the title slide.
 * @param dependencies Host branding dependency.
 * @returns Nothing; mutates the supplied slide.
 */
function baseSlide(
  slide: any,
  pptx: any,
  theme: any,
  number: number,
  total: number,
  dependencies: FileToolDependencies
): void {
  // Base styling is centralized so every layout remains visually consistent.
  slide.background = { color: theme.background };
  slide.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: 0,
    w: 13.333,
    h: 0.06,
    fill: { color: theme.accent },
    line: { color: theme.accent },
  });
  if (number)
    slide.addText(`${number}/${total - 1}`, {
      x: 11.9,
      y: 7.1,
      w: 0.8,
      h: 0.2,
      fontSize: 7,
      align: "right",
      color: theme.muted,
      margin: 0,
    });
  // Logos are host-owned and omitted cleanly when branding is unavailable.
  const logo = dependencies.getLogo?.({
    forDarkBackground: theme.background === "0F172A",
    format: "dataUri",
  });
  if (typeof logo === "string")
    slide.addImage({
      data: logo,
      x: 11.5,
      y: 6.8,
      w: 1.15,
      h: 0.2,
      transparency: 75,
    });
}
